export const SET_SUPERHERO = "SET_SUPERHERO";

export const TOGGLE_COMICS = "TOGGLE_COMICS";

export const TOGGLE_SERIES = "TOGGLE_SERIES";

export const TOGGLE_EVENTS = "TOGGLE_EVENTS";

export const REQUEST_HEROINFO = "REQUEST_HEROINFO";

export const RECEIVE_HEROINFO = "RECEIVE_HEROINFO";

export const REQUEST_COMICS = "REQUEST_COMICS";

export const RECEIVE_COMICS = "RECEIVE_COMICS";

export const REQUEST_SERIES = "REQUEST_SERIES";

export const RECEIVE_SERIES = "RECEIVE_SERIES";

export const REQUEST_EVENTS = "REQUEST_EVENTS";

export const RECEIVE_EVENTS = "RECEIVE_EVENTS";

export const RESET_UI = "RESET_UI";
